// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfppyN4KktPnd5TIzuT1KoiGgZc3YEDC8',
    appId: '1:321503398049:web:7ef135cc6e00bc8d36c8e0',
    messagingSenderId: '321503398049',
    projectId: 'budget-tracker-50c3b',
    authDomain: 'budget-tracker-50c3b.firebaseapp.com',
    storageBucket: 'budget-tracker-50c3b.appspot.com',
    measurementId: 'G-5MMYJPJQMW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEqk2Xsiz5zndI8dyApc4OREmmOAu8gu0',
    appId: '1:321503398049:android:f31d1a6134e6928536c8e0',
    messagingSenderId: '321503398049',
    projectId: 'budget-tracker-50c3b',
    storageBucket: 'budget-tracker-50c3b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-oYaDs-EH6OaLY01IXoH_F9F2VjdxTN0',
    appId: '1:321503398049:ios:3bdfd531674163e736c8e0',
    messagingSenderId: '321503398049',
    projectId: 'budget-tracker-50c3b',
    storageBucket: 'budget-tracker-50c3b.appspot.com',
    iosClientId: '321503398049-8p0ru6ko9qn04ij0u3njldjesnunqtui.apps.googleusercontent.com',
    iosBundleId: 'com.example.budgetTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-oYaDs-EH6OaLY01IXoH_F9F2VjdxTN0',
    appId: '1:321503398049:ios:3bdfd531674163e736c8e0',
    messagingSenderId: '321503398049',
    projectId: 'budget-tracker-50c3b',
    storageBucket: 'budget-tracker-50c3b.appspot.com',
    iosClientId: '321503398049-8p0ru6ko9qn04ij0u3njldjesnunqtui.apps.googleusercontent.com',
    iosBundleId: 'com.example.budgetTracker',
  );
}
